{
  :en => {
    :kopal => {
      :about_me => "About me",
      :aliases => "Aliases",
      :back_to_homepage => "Back to homepage",
      :city => "City",
      :country => "Country",
      :date_of_birth => "Date of Birth",
      :dont_show => "Do not show",
      :edit_profile => "Edit profile",
      :edit_your_profile => "Edit your profile.",
      :email => "E-mail",
      :female => "Female",
      :friend_count => {:one => 'Friend (%{count})', :other => 'Friends (%{count})'},
      :gender => "Gender",
      :go_back_to_homepage => "Go back to homepage.",
      :hello => "Hello",
      :hello_world => "Hello, world!",
      :home => "Home",
      :male => "Male",
      :name => "Name",
      :no => "No",
      :preferred_calling_name => "Preferred Calling Name",
      :profile_homepage_of_person => "Profile homepage of %{person}.",
      :real_name => "Real name",
      :separate_aliases_by_newline => "Separate aliases by newline.",
      :show_date_of_birth => "Show date of birth",
      :show_email => "Show email",
      :show_full_dob => "Show full date of birth",
      :show_only_age => "Show only age",
      :show_only_month_and_date => "Show only month and date",
      :sign_in => "Sign-in",
      :sign_out => "Sign-out",
      :sign_up => "Sign-up",
      :status_message => "Status message",
      :user_has_not_yet_created_her_identity => "User has not yet created her identity.",
      :view_friends_of_person => "View friends of %{person}.",
      :year => { :one => "Year", :other => "Years"},
      :yes => "Yes",
    }
  }
}

