{
  :en => {
    :hello => "Hello",
    :hello_world => "Hello, world!",
    :name => "Name",
    :real_name => "Real name",
    :aliases => "Aliases",
    :preferred_calling_name => "Preferred Calling Name",
    :about_me => "About me",
    :gender => "Gender",
    :date_of_birth => "Date of Birth",
    :city => "City",
    :country => "Country",
    :show_date_of_birth => "Show date of birth",
    :show_only_age => "Show only age",
    :dont_show => "Do not show",
    :show_only_month_and_date => "Show only month and date",
    :show_full_dob => "Show full date of birth",
    :male => "Male",
    :female => "Female",
    :separate_aliases_by_newline => "Separate aliases by newline.",
    :home => "Home",
    :friend => {:one => 'Friend ({{count}})', :other => 'Friends ({{count}})'},
    :view_friends_of_person => "View friends of {{person}}.",
    :profile_homepage_of_person => "Profile homepage of {{person}}.",
    :sign_in => "Sign-in",
    :sign_out => "Sign-out",
    :sign_up => "Sign-up",
    :edit_profile => "Edit profile",
    :edit_your_profile => "Edit your profile.",
    :email => "E-mail",
    :show_email => "Show email",
    :yes => "Yes",
    :no => "No",
    :status_message => "Status message",
    :back_to_homepage => "Back to homepage",
    :go_back_to_homepage => "Go back to homepage.",
    :user_has_not_yet_created_her_identity => "User has not yet created her identity.",
    :year => { :one => "Year", :other => "Years"}
  }
}

