source 'http://rubygems.org'

#Kopal
gem 'kopal', :path => '../kopal'
gem 'kopal-rails', :path => '../kopal-rails'
#kopal development dependency gems as they are not being included from there
gem 'factory_girl_rails'
gem 'bson_ext'

# Asset template engines
gem 'json'
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'
gem 'johnson' #for execjs

gem 'jquery-rails'

gem 'ruby-debug'
